[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"

[services.web]
buildCommand = "npm run build"
watch = [
    "app/**",
    "components/**",
    "lib/**",
    "public/**"
]

[env]
NODE_ENV = "production"
PORT = "3000"
